name: Compliance1

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

permissions:
  pull-requests: write

jobs:
  my-job:
    name: Semantics
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'Chad'
    - name: output the memory
      run: |
        echo ${{ steps.hello.outputs.memory }}
        echo "total memory successfully output"
